services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-local
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT_API_KEY: "th3s3cr3tk3y"
